- name: Restart Unbound
  ansible.builtin.service:
    name: unbound
    state: restarted

- name: Restart Pihole-FTL
  ansible.builtin.service:
    name: pihole-FTL
    state: restarted

- name: "Update Pi-hole gravity"
  ansible.builtin.command: "pihole -g"
  changed_when: true

- name: Apply netplan
  ansible.builtin.command: netplan apply
  changed_when: false
