- name: Restart Unbound
  ansible.builtin.service:
    name: unbound
    state: restarted

- name: Restart Pihole-FTL
  ansible.builtin.service:
    name: pihole-FTL
    state: restarted

- name: "Update Pi-hole gravity"
  ansible.builtin.command: "pihole -g"
  changed_when: true

- name: "Set Pi-hole Web Interface Password"
  ansible.builtin.command: "pihole -a -p {{ vault_pihole_web_password }}"
  no_log: true
  changed_when: false
