$ANSIBLE_VAULT;1.1;AES256
66306338633964306265306534343634376636613431306431623737303761656265366231613465
3639383238343535323333303061306565613361313230360a366434373662393963346433396164
34323565373661336439636530626538613661376538333936313963663534616161373030363832
6532323935313032630a656365623336393664333233356130396434663630393063353165306436
32343735666138323033396331303262663464353639366135333530313436303635396661393435
62346234396365376265653237306331303962313831666334323939613064393236616232356166
35633265326663393432393933313234653266396230366432373731323133623937333162366664
62646636303538623832343636306339366635643937613866623534636233656264343063336135
33363134386366383361343866393633653231343638613830313630303364353535373735383431
66366437623561616635333730646334326161343461653835343761303761333964333337636166
65336138636133373231623738663537383736373230356138336561613830636434613837353631
35636462363031383538393435663466363462323133373766313366666535386633653633306230
31336665336665383165363265353930363231623766343264623930633133646563
