---
- name: "Inject Local DNS Records into /etc/hosts"
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED DOMAINS"
    block: |
      {% for item in pihole_records_local %}
      {{ item.ip }} {{ item.name }}
      {% endfor %}
  notify: Restart Pihole-DNS
  tags: records
