---
- name: Setup lxc "tang"
  hosts: tang
  become: true
  roles:
    - { role: update, tags: ['update'] }
    - { role: ufw_base, tags: ['ufw'] }
    - { role: ufw_tang, tags: ['ufw'] }
    - { role: ufw_enable, tags: ['ufw'] }
    - { role: tang, tags: ['tang'] }
