---

- name: Setup dns servers
  hosts: dns_group
  become: true
  roles:
    - { role: common, tags: ['common'] }
    - { role: ufw_pihole, tags: ['pihole', 'pihole_ufw'] }
    - { role: ufw_enable, tags: ['pihole'] }
    - { role: pihole_records, tags: ['pihole', 'pihole_records'] }
    - { role: pihole, tags: ['pihole'] }
    - { role: keepalived_pihole, tags: ['pihole', 'keepalived'] }

- name: Setup lxc "tang"
  hosts: tang
  become: true
  roles:
    - { role: common, tags: ['common'] }
    - { role: update, tags: ['update'] }
    - { role: ufw_base, tags: ['ufw'] }
    - { role: ufw_tang, tags: ['ufw'] }
    - { role: ufw_enable, tags: ['ufw'] }
    - { role: tang, tags: ['tang'] }
