---
- name: Setup lxc "runner-alpha"
  hosts: runner_group
  become: yes
  roles:
    - { role: ufw_base, tags: ['ufw'] }
    - { role: ufw_runner, tags: ['ufw'] }
    - { role: ufw_enable, tags: ['ufw'] }
    - { role: update, tags: ['update'] }
    - { role: docker, tags: ['docker'] }
    - { role: github_runner, tags: ['runner'] }
