---
- name: Setup lxc "ops"
  hosts: ops
  become: yes
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: gitea, tags: ['gitea'] }

- name: Setup lxc "tang"
  hosts: tang
  become: yes
  roles:
    - { role: tang,   tags: ['tang'] }
