---
- name: Update apt cache and upgrade all packages
  apt:
    update_cache: yes
    upgrade: dist
    force_apt_get: yes

- name: Remove unused dependency packages (autoremove)
  apt:
    autoremove: yes
    purge: yes

- name: Clean up local repository (autoclean)
  apt:
    autoclean: yes

- name: Check if a reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot the server if kernel was updated
  reboot:
    msg: "Reboot initiated by Ansible"
  when: reboot_required_file.stat.exists
