---
- name: Update apt cache and upgrade all packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Remove unused dependency packages (autoremove)
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Clean up local repository (autoclean)
  ansible.builtin.apt:
    autoclean: true

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: update_reboot_required_file

- name: Reboot the server if kernel was updated
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
  when: update_reboot_required_file.stat.exists
