$ANSIBLE_VAULT;1.1;AES256
34633363366130343538303831343162333639303335363539323738643430383730383539353630
3130383836343634363335373531383833366363333565360a336162666331663130656530343630
30363336643463353435663833646364333633303533653637633263633630383166346263336163
6138376133623465340a643830653439323662633831623363663236373163666265363766623038
65336165353730613037313665393734326464376234306436393531623262366565336464336536
35353039623231616332373135636131656661383363303439636230343866306330333830323762
33663862376165333765313861663565663266326631343766353365313463386632656232363130
36616632383939643730396264313930383164653236306463323132643366643133643631656265
39653065616266343535353737386635393636373765346662346634306137633934323736336537
3862646462346636613639393964313134333565373463303964
