$ANSIBLE_VAULT;1.1;AES256
64633161663763643065626363386365333864356466343930393366383065616134623534363232
3031663037313739626261643563376663313932303563640a646565653964643731316633323839
38366161306132313361366338653032333434306364313830383533306438613034383535353362
6436363539303338330a666161316263373265336638393262643930663932366666623434303838
36393936353739306338363561626363383330653163336666343966383937326236313736333532
61666564373966373638343262616334366533363132373065383239623434613365623964356237
37653934306666336361383661333961303262336666356431373830633064313334636539303539
65323536376534636236393534393539303136373339653931656237346666646434613837643462
63306139376361636331653064346236303333303933323366656462363436613363386634333135
3633663361373835346236666438383931613035313433386361
